baseURL = "/"
languageCode = "en-us"
title = "My Ultimate Guide For Everything"
theme = "silhouette-hugo"
googleAnalytics = "UA-133483765-1"
copyright = "Copyright © 2019, My Ultimate Guide For Everything; all rights reserved."
paginate = 7
enableRobotsTXT = true


[params]
    author = "My Ultimate Guide For Everything"
    description = "**Disclaimer:** Products introduced by this blog are only recommendations and it does not mean you should purchase them without doing your own research or using your logic :-)"
    githubUsername = "#"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    contentSharing = "Theme powered by silhouette-hugo https://github.com/mattbutton/silhouette-hugo"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about"
    name = "About"
    weight = 3

[[menu.main]]
    url = "/cpa_privacy_policy"
    name = "Privacy Policy"
    weight = 4    


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:info@comparepriceacross.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/comppriceacross/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://business.facebook.com/Compare-price-across-2279037415758796/"
    name = "facebook-square"
    weight = 3

[social]
twitter = "comparepriceacross"

[markup.goldmark.renderer]
  unsafe = true
